components:
    schemas:
        Error:
            properties:
                code:
                    description: Error code
                    type: integer
                error:
                    description: Error message
                    type: string
            required:
                - error
            type: object
    securitySchemes:
        fastly_api_key:
            description: Fastly API key for authentication
            in: header
            name: Fastly-Key
            type: apiKey
info:
    contact:
        email: support@fastly.com
        name: Fastly API Support
        url: https://developer.fastly.com
    description: |-
        Via the Fastly API you can perform any of the operations that are possible within the management console, including creating services, domains, and backends; and configuring rules or uploading your own application code, as well as perform account operations such as user administration and billing reports.

        The API is organized into collections of endpoints that allow manipulation of objects related to Fastly services and accounts.

        For the most accurate and up-to-date API reference content, visit [developer.fastly.com/reference/api/](https://developer.fastly.com/reference/api/).
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT
    title: Fastly API
    version: 1.0.0
openapi: 3.0.3
paths:
    /automation-tokens:
        post:
            description: |
                Creates a new automation token.
                > **Authorization**: Requires [API token](/reference/api/auth-tokens).
            operationId: createAutomationToken
            requestBody:
                content:
                    application/json:
                        schema:
                            description: Request body for Create Automation Token
                            type: object
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                description: Response for 201 Created
                                type: object
                    description: Created
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Bad Request
                "401":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Unauthorized
                "500":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Internal Server Error
            security:
                - fastly_api_key: []
            summary: Create Automation Token
            tags:
                - Authentication tokens
    /service:
        get:
            description: "**[\U0001F517 latest documentation](https://developer.fastly.com/reference/api/services/service/#list-services)**\n\n> **Authorization**: [API token](/reference/api/auth-tokens) with at least [Engineer](https://docs.fastly.com/en/guides/configuring-user-roles-and-permissions\") permissions.\n"
            operationId: listServices
            parameters:
                - description: 'Query parameter: direction'
                  in: query
                  name: direction
                  schema:
                    type: string
                - description: 'Query parameter: page'
                  in: query
                  name: page
                  schema:
                    type: string
                - description: 'Query parameter: per_page'
                  in: query
                  name: per_page
                  schema:
                    type: string
                - description: 'Query parameter: sort'
                  in: query
                  name: sort
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                description: Response for 200 OK
                                type: object
                    description: OK
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Bad Request
                "401":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Unauthorized
                "500":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Internal Server Error
            security:
                - fastly_api_key: []
            summary: List services
            tags:
                - Services
    /service/{service_id}/version/{version_id}/backend:
        get:
            description: |
                List all backends for a particular service and version.
                > **Authorization**: [API token](/reference/api/auth-tokens) with at least [Engineer](https://docs.fastly.com/en/guides/configuring-user-roles-and-permissions") permissions.
            operationId: listBackends
            parameters:
                - description: The service_id identifier
                  in: path
                  name: service_id
                  required: true
                  schema:
                    type: string
                - description: The version_id identifier
                  in: path
                  name: version_id
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                description: Response for 200 OK
                                type: object
                    description: OK
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Bad Request
                "401":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Unauthorized
                "500":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Internal Server Error
            security:
                - fastly_api_key: []
            summary: List backends
            tags:
                - Services
    /service/{service_id}/version/{version_id}/condition:
        get:
            description: |
                Gets all conditions for a particular service and version.
                > **Authorization**: [API token](/reference/api/auth-tokens) with at least [Engineer](https://docs.fastly.com/en/guides/configuring-user-roles-and-permissions") permissions.
            operationId: listConditions
            parameters:
                - description: The service_id identifier
                  in: path
                  name: service_id
                  required: true
                  schema:
                    type: string
                - description: The version_id identifier
                  in: path
                  name: version_id
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                description: Response for 200 OK
                                type: object
                    description: OK
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Bad Request
                "401":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Unauthorized
                "500":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                    description: Internal Server Error
            security:
                - fastly_api_key: []
            summary: List conditions
            tags:
                - VCL objects
security:
    - fastly_api_key: []
servers:
    - description: Fastly API production server
      url: https://api.fastly.com
tags:
    - description: Access control lists related operations
      name: Access control lists
    - description: Account related operations
      name: Account
    - description: Alerts related operations
      name: Alerts
    - description: Authentication tokens related operations
      name: Authentication tokens
    - description: Dictionaries related operations
      name: Dictionaries
    - description: Domain metrics related operations
      name: Domain metrics
    - description: Domains on Fastly related operations
      name: Domains on Fastly
    - description: Edge data storage related operations
      name: Edge data storage
    - description: Fastly DDoS Protection Events related operations
      name: Fastly DDoS Protection Events
    - description: Load balancing related operations
      name: Load balancing
    - description: Metrics and stats related operations
      name: Metrics and stats
    - description: Mutual TLS related operations
      name: Mutual TLS
    - description: Observability related operations
      name: Observability
    - description: Origin metrics related operations
      name: Origin metrics
    - description: Products related operations
      name: Products
    - description: Publishing related operations
      name: Publishing
    - description: Purging related operations
      name: Purging
    - description: Real-time logging related operations
      name: Real-time logging
    - description: Security related operations
      name: Security
    - description: Services related operations
      name: Services
    - description: Subscriber Provided Prefix (SPP) related operations
      name: Subscriber Provided Prefix (SPP)
    - description: TLS related operations
      name: TLS
    - description: Utilities related operations
      name: Utilities
    - description: VCL objects related operations
      name: VCL objects
